module.exports = {
    t,
    lan,
};

var language = "";
var l2l = {
    "zh-CN": "zh-HANS",
    "zh-SG": "zh-HANS",
    "zh-TW": "zh-HANT",
    "zh-HK": "zh-HANT",
    "en-GB": "en",
    "en-UK": "en",
};

/**
 * 切换语言
 * @param {string} lan 语言
 */
function lan(lan) {
    language = lan;
}

/**
 * 翻译
 * @param {string} text 原文字
 * @returns 翻译后的文字
 */
function t(text) {
    if (l2l[language] == "zh-HANS") return text;
    return obj?.[text]?.[language] || obj?.[text]?.[l2l[language]] || text;
}

var obj = {
    "服务正在下载中……": { en: "Service download is in progress ......", "zh-HANT": "服務正在下載中……" },
    服务下载已取消: { en: "Service download has been cancelled", "zh-HANT": "服務下載已取消" },
    服务已下载: { en: "Service has been downloaded", "zh-HANT": "服務已下載" },
    "，正准备安装相关的依赖，请允许安装": {
        en: ", is preparing to install the relevant dependencies, please allow installation",
        "zh-HANT": "，正準備安裝相關的依賴，請允許安裝",
    },
    自动搜索: { en: "auto search", "zh-HANT": "自動搜索" },
    截屏搜索: { en: "Screenshot search", "zh-HANT": "截屏搜索" },
    选中搜索: { en: "Selected search", "zh-HANT": "選中搜索" },
    剪贴板搜索: { en: "clipboard search", "zh-HANT": "剪貼板搜索" },
    失焦关闭: { en: "Out of focus off", "zh-HANT": "失焦關閉" },
    主界面: { en: "Main screen", "zh-HANT": "主界面" },
    搜索界面: { en: "Search screen", "zh-HANT": "搜索界面" },
    浏览器打开: { en: "Browser open", "zh-HANT": "瀏覽器打開" },
    主页面: { en: "Main Page", "zh-HANT": "主頁面" },
    设置: { en: "Settings", "zh-HANT": "設置" },
    教程帮助: { en: "Tutorial help", "zh-HANT": "教程幫助" },
    重启: { en: "Reboot", "zh-HANT": "重啟" },
    退出: { en: "Exit", "zh-HANT": "退出" },
    已经在后台启动: { en: "Already started in background", "zh-HANT": "已經在後台啟動" },
    服务未下载: { en: "Service not downloaded", "zh-HANT": "服務未下載" },
    "离线OCR 服务未安装": { en: "Offline OCR service is not installed", "zh-HANT": "離線OCR 服務未安裝" },
    需要下载才能使用: { en: "Need to download to use", "zh-HANT": "需要下載才能使用" },
    不再提示: { en: "No more prompts", "zh-HANT": "不再提示" },
    "下载(约": { en: "Download (approx.", "zh-HANT": "下載(約" },
    "前往 设置": { en: "Go to Settings", "zh-HANT": "前往 設置" },
    取消: { en: "Cancel", "zh-HANT": "取消" },
    服务需要升级: { en: "Service needs to be upgraded", "zh-HANT": "服務需要升級" },
    "离线OCR 服务版本较旧": { en: "Older version of offline OCR service", "zh-HANT": "離線OCR 服務版本較舊" },
    服务下载失败: { en: "Service download failed", "zh-HANT": "服務下載失敗" },
    "离线OCR 服务版本下载失败": {
        en: "Offline OCR service version download failed",
        "zh-HANT": "離線OCR 服務版本下載失敗",
    },
    请前往网站手动下载: { en: "Please go to the website to download manually", "zh-HANT": "請前往網站手動下載" },
    警告: { en: "Warning", "zh-HANT": "警告" },
    无法识别二维码: { en: "QR code not recognised", "zh-HANT": "無法識別二維碼" },
    请尝试重新识别: { en: "Please try to re-identify", "zh-HANT": "請嘗試重新識別" },
    选择要打开应用的位置: { en: "Select where you want to open the app", "zh-HANT": "選擇要打開應用的位置" },
    选择要保存的位置: { en: "Select a location to save to", "zh-HANT": "選擇要保存的位置" },
    图像: { en: "Image", "zh-HANT": "圖像" },
    保存图像失败: { en: "Failed to save image", "zh-HANT": "保存圖像失敗" },
    用户已取消保存: { en: "User has cancelled the save", "zh-HANT": "用戶已取消保存" },
    视频: { en: "Video", "zh-HANT": "視頻" },
    保存视频失败: { en: "Failed to save video", "zh-HANT": "保存視頻失敗" },
    错误: { en: "Error", "zh-HANT": "錯誤" },
    "已恢复默认设置，部分设置需要重启": {
        en: "Default settings have been restored, some settings need to be rebooted",
        "zh-HANT": "已恢復默認設置，部分設置需要重啟",
    },
    生效: { en: "Effective", "zh-HANT": "生效" },
    稍后: { en: "Later", "zh-HANT": "稍後" },
    关于: { en: "About", "zh-HANT": "關於" },
    服务: { en: "Services", "zh-HANT": "服務" },
    隐藏: { en: "Hide", "zh-HANT": "隱藏" },
    隐藏其他: { en: "Hide other", "zh-HANT": "隱藏其他" },
    全部显示: { en: "Show all", "zh-HANT": "全部顯示" },
    文件: { en: "File", "zh-HANT": "文件" },
    保存到历史记录: { en: "Save to history", "zh-HANT": "保存到歷史記錄" },
    其他编辑器打开: { en: "Open with other editor", "zh-HANT": "其他編輯器打開" },
    "打开方式...": { en: "Open as...", "zh-HANT": "打開方式..." },
    关闭: { en: "Close", "zh-HANT": "關閉" },
    编辑: { en: "Edit", "zh-HANT": "編輯" },
    打开链接: { en: "Open link", "zh-HANT": "打開鏈接" },
    搜索: { en: "Search", "zh-HANT": "搜索" },
    翻译: { en: "Translate", "zh-HANT": "翻譯" },
    撤销: { en: "Undo", "zh-HANT": "撤銷" },
    重做: { en: "Redo", "zh-HANT": "重做" },
    剪切: { en: "Cut", "zh-HANT": "剪切" },
    复制: { en: "Copy", "zh-HANT": "複製" },
    粘贴: { en: "Paste", "zh-HANT": "粘貼" },
    删除: { en: "Delete", "zh-HANT": "刪除" },
    全选: { en: "Select All", "zh-HANT": "全選" },
    自动删除换行: { en: "Auto Delete Line Feed", "zh-HANT": "自動刪除換行" },
    查找: { en: "find", "zh-HANT": "查找" },
    替换: { en: "Replace", "zh-HANT": "替換" },
    自动换行: { en: "Auto Line Feed", "zh-HANT": "自動換行" },
    拼写检查: { en: "spell check", "zh-HANT": "拼寫檢查" },
    朗读: { en: "Read aloud", "zh-HANT": "朗讀" },
    开始朗读: { en: "Start reading aloud", "zh-HANT": "開始朗讀" },
    停止朗读: { en: "Stop reading aloud", "zh-HANT": "停止朗讀" },
    浏览器: { en: "Browser", "zh-HANT": "瀏覽器" },
    后退: { en: "Back", "zh-HANT": "後退" },
    前进: { en: "Forward", "zh-HANT": "前進" },
    刷新: { en: "Refresh", "zh-HANT": "刷新" },
    停止加载: { en: "Stop loading", "zh-HANT": "停止加載" },
    视图: { en: "View", "zh-HANT": "視圖" },
    重新加载: { en: "Reload", "zh-HANT": "重新加載" },
    强制重载: { en: "Force Reload", "zh-HANT": "強制重載" },
    开发者工具: { en: "Developer Tools", "zh-HANT": "開發者工具" },
    历史记录: { en: "History", "zh-HANT": "歷史記錄" },
    实际大小: { en: "Actual size", "zh-HANT": "實際大小" },
    放大: { en: "Zoom In", "zh-HANT": "放大" },
    缩小: { en: "Zoom out", "zh-HANT": "縮小" },
    全屏: { en: "Full screen", "zh-HANT": "全屏" },
    窗口: { en: "Window", "zh-HANT": "窗口" },
    最小化: { en: "Minimise", "zh-HANT": "最小化" },
    置于最前面: { en: "Place at top", "zh-HANT": "置於最前面" },
    帮助: { en: "Help", "zh-HANT": "幫助" },
    保存图像成功: { en: "Saved image successfully", "zh-HANT": "保存圖像成功" },
    已保存图像到: { en: "Saved image to", "zh-HANT": "已保存圖像到" },
    "eSearch - 主界面": { en: "eSearch - Main", "zh-HANT": "eSearch - 主界面" },
    "eSearch - 截屏": { en: "eSearch - Screen capture", "zh-HANT": "eSearch - 截屏" },
    "eSearch - 设置": { en: "eSearch - Setting", "zh-HANT": "eSearch - 設置" },
    "eSearch - 帮助": { en: "eSearch - Help", "zh-HANT": "eSearch - 幫助" },
    "eSearch - 浏览器": { en: "eSearch - Browser", "zh-HANT": "eSearch - 瀏覽器" },
    "eSearch - ding": { en: "eSearch - ding", "zh-HANT": "eSearch - ding" },
    "eSearch - 录屏": { en: "eSearch - Recorder", "zh-HANT": "eSearch - 錄屏" },
    上一个匹配: { en: "previous match", "zh-HANT": "上一個匹配" },
    下一个匹配: { en: "next match", "zh-HANT": "下一個匹配" },
    启动: { en: "boot", "zh-HANT": "啟動" },
    开机自启动: { en: "boot-up", "zh-HANT": "開機自啟動" },
    启动提示: { en: "boot prompt", "zh-HANT": "啟動提示" },
    启动时系统通知提示启动: { en: "System notification to start at boot", "zh-HANT": "啟動時系統通知提示啟動" },
    语言: { en: "Language", "zh-HANT": "語言" },
    使用系统语言: { en: "use system language", "zh-HANT": "使用系統語言" },
    快捷键: { en: "shortcuts", "zh-HANT": "快捷鍵" },
    全局: { en: "global", "zh-HANT": "全局" },
    截屏: { en: "Screenshot", "zh-HANT": "截屏" },
    主搜索功能: { en: "Main search function", "zh-HANT": "主搜索功能" },
    自动搜索排除: { en: "Automatic search exclusion", "zh-HANT": "自動搜索排除" },
    "若选中的文字符合文本框的规则，将使用截屏搜索而不是选择搜索": {
        en: "if the selected text matches the rules of the text box, a screenshot search will be used instead of a select search",
        "zh-HANT": "若選中的文字符合文本框的規則，將使用截屏搜索而不是選擇搜索",
    },
    "换行新建项目，支持正则表达式": {
        en: "New item with line feed, regular expression support",
        "zh-HANT": "換行新建項目，支持正則表達式",
    },
    使用选区内容: { en: "Using the contents of a selection", "zh-HANT": "使用選區內容" },
    全局样式: { en: "global styles", "zh-HANT": "全局樣式" },
    毛玻璃效果: { en: "Glass effect", "zh-HANT": "毛玻璃效果" },
    模糊: { en: "blur", "zh-HANT": "模糊" },
    不透明度: { en: "Opacity", "zh-HANT": "不透明度" },
    深色模式: { en: "dark mode", "zh-HANT": "深色模式" },
    跟随系统: { en: "following system", "zh-HANT": "跟隨系統" },
    浅色: { en: "light", "zh-HANT": "淺色" },
    深色: { en: "dark", "zh-HANT": "深色" },
    全局缩放: { en: "global zoom", "zh-HANT": "全局縮放" },
    字体: { en: "Font", "zh-HANT": "字體" },
    主要字体: { en: "main fonts", "zh-HANT": "主要字體" },
    "（适用于主界面等文字字体）": {
        en: "(for text fonts such as main interface)",
        "zh-HANT": "（適用於主界面等文字字體）",
    },
    等宽字体: { en: "Equal width fonts", "zh-HANT": "等寬字體" },
    "（适用于截屏时数字、颜色代码等字体）": {
        en: "(for fonts such as numbers, colour codes, etc. when taking screenshots)",
        "zh-HANT": "（適用於截屏時數字、顏色代碼等字體）",
    },
    工具栏: { en: "Toolbar", "zh-HANT": "工具欄" },
    工具栏跟随: { en: "toolbar follow", "zh-HANT": "工具欄跟隨" },
    展示内容优先: { en: "priority for displaying content", "zh-HANT": "展示內容優先" },
    效率优先: { en: "efficiency first", "zh-HANT": "效率優先" },
    按钮大小: { en: "Button size", "zh-HANT": "按鈕大小" },
    按钮: { en: "Button", "zh-HANT": "按鈕" },
    图标比例: { en: "icon scale", "zh-HANT": "圖標比例" },
    取色器: { en: "colour picker", "zh-HANT": "取色器" },
    大小: { en: "size", "zh-HANT": "大小" },
    取色器大小: { en: "color picker size", "zh-HANT": "取色器大小" },
    像素大小: { en: "pixel size", "zh-HANT": "像素大小" },
    默认格式: { en: "default format", "zh-HANT": "默認格式" },
    框选: { en: "Boxed", "zh-HANT": "框選" },
    框选颜色: { en: "box color", "zh-HANT": "框選顏色" },
    遮罩颜色: { en: "mask color", "zh-HANT": "遮罩顏色" },
    选区颜色: { en: "selection color", "zh-HANT": "選區顏色" },
    光标: { en: "cursor", "zh-HANT": "光標" },
    "以(0,0)为起点": { en: "starting at (0,0)", "zh-HANT": "以(0,0)為起點" },
    "以(1,1)为起点": { en: "starting at (1,1)", "zh-HANT": "以(1,1)為起點" },
    大小坐标: { en: "size coordinates", "zh-HANT": "大小坐標" },
    显示四角坐标: { en: "display quadrangular coordinates", "zh-HANT": "顯示四角坐標" },
    "（截屏框选附近除了框选大小，还会加上左上角和右下角坐标）": {
        en: "(screenshot boxed near will add top-left and bottom-right coordinates in addition to the boxed size)",
        "zh-HANT": "（截屏框選附近除了框選大小，還會加上左上角和右下角坐標）",
    },
    框选后默认操作: { en: "default action after frame", "zh-HANT": "框選後默認操作" },
    "框选完鼠标松开一瞬间，执行操作": {
        en: "action to be performed the moment the mouse is released after framing",
        "zh-HANT": "框選完鼠標鬆開一瞬間，執行操作",
    },
    无: { en: "none", "zh-HANT": "無" },
    "OCR(文字识别)": { en: "OCR (text recognition)", "zh-HANT": "OCR(文字識別)" },
    以图搜图: { en: "Search by image", "zh-HANT": "以圖搜圖" },
    QR码: { en: "QR code", "zh-HANT": "QR碼" },
    标记: { en: "Marker", "zh-HANT": "標記" },
    其他应用打开: { en: "open in other apps", "zh-HANT": "其他應用打開" },
    放在屏幕上: { en: "Place on screen", "zh-HANT": "放在屏幕上" },
    保存: { en: "Save", "zh-HANT": "保存" },
    自动框选: { en: "Automatically frame", "zh-HANT": "自動框選" },
    "使用OpenCV自动识别边缘轮廓（测试版）": {
        en: "Automatic edge contour recognition using OpenCV (beta)",
        "zh-HANT": "使用OpenCV自動識別邊緣輪廓（測試版）",
    },
    启用自动框选: { en: "Enable auto-framing", "zh-HANT": "啟用自動框選" },
    边缘识别高级设置: { en: "Advanced settings for edge recognition", "zh-HANT": "邊緣識別高級設置" },
    最小阈值: { en: "minimum threshold", "zh-HANT": "最小閾值" },
    最大阈值: { en: "maximum threshold", "zh-HANT": "最大閾值" },
    图像编辑: { en: "Image editing", "zh-HANT": "圖像編輯" },
    默认属性: { en: "default properties", "zh-HANT": "默認屬性" },
    填充颜色: { en: "Fill color", "zh-HANT": "填充顏色" },
    边框颜色: { en: "border color", "zh-HANT": "邊框顏色" },
    边框宽度: { en: "border width", "zh-HANT": "邊框寬度" },
    画笔颜色: { en: "brush color", "zh-HANT": "畫筆顏色" },
    画笔粗细: { en: "brush thickness", "zh-HANT": "畫筆粗細" },
    复制偏移: { en: "copy offset", "zh-HANT": "複製偏移" },
    "复制完一个元素后，为了分辨，可以让其偏移": {
        en: "after copying an element, you can offset it to distinguish",
        "zh-HANT": "複製完一個元素後，為了分辨，可以讓其偏移",
    },
    x轴: { en: "x-axis", "zh-HANT": "x軸" },
    y轴: { en: "y-axis", "zh-HANT": "y軸" },
    快速截屏: { en: "quick screenshot", "zh-HANT": "快速截屏" },
    保存到: { en: "save to", "zh-HANT": "保存到" },
    剪贴板: { en: "clipboard", "zh-HANT": "剪貼板" },
    目录: { en: "directory", "zh-HANT": "目錄" },
    获取保存路径: { en: "get save path", "zh-HANT": "獲取保存路徑" },
    录屏: { en: "record screen", "zh-HANT": "錄屏" },
    自动录制: { en: "auto record", "zh-HANT": "自動錄製" },
    开启自动录制: { en: "Enable auto-recording", "zh-HANT": "開啟自動錄製" },
    录制: { en: "record", "zh-HANT": "錄製" },
    视频比特率: { en: "video bitrate", "zh-HANT": "視頻比特率" },
    屏幕: { en: "screen", "zh-HANT": "屏幕" },
    帧率: { en: "frame rate", "zh-HANT": "幀率" },
    高级: { en: "Advanced", "zh-HANT": "高級" },
    "换行新建项目，%s代替关键字": {
        en: "new item in new line, %s instead of keyword",
        "zh-HANT": "換行新建項目，%s代替關鍵字",
    },
    摄像头: { en: "camera", "zh-HANT": "攝像頭" },
    默认开启: { en: "default on", "zh-HANT": "默認開啟" },
    记录开启状态: { en: "record on status", "zh-HANT": "記錄開啟狀態" },
    音频: { en: "Audio", "zh-HANT": "音頻" },
    文件名称: { en: "file name", "zh-HANT": "文件名稱" },
    时间: { en: "time", "zh-HANT": "時間" },
    "预览:": { en: "Preview:", "zh-HANT": "預覽:" },
    时间代码: { en: "timecode", "zh-HANT": "時間代碼" },
    四位数年: { en: "four-digit year", "zh-HANT": "四位數年" },
    末两位年: { en: "Last two digit year", "zh-HANT": "末兩位年" },
    月: { en: "month", "zh-HANT": "月" },
    日: { en: "day", "zh-HANT": "日" },
    星期: { en: "Week", "zh-HANT": "星期" },
    "24小时制小时": { en: "24-hour hour", "zh-HANT": "24小時制小時" },
    "12小时制小时": { en: "12-hour hour", "zh-HANT": "12小時制小時" },
    分: { en: "minutes", "zh-HANT": "分" },
    秒: { en: "seconds", "zh-HANT": "秒" },
    毫秒: { en: "milliseconds", "zh-HANT": "毫秒" },
    jpg质量: { en: "jpg quality", "zh-HANT": "jpg質量" },
    编辑器: { en: "editor", "zh-HANT": "編輯器" },
    字体大小: { en: "font size", "zh-HANT": "字體大小" },
    记住主界面字体大小: { en: "remember main interface font size", "zh-HANT": "記住主界面字體大小" },
    样式: { en: "style", "zh-HANT": "樣式" },
    Tab制表符宽度: { en: "Tab tab width", "zh-HANT": "Tab製表符寬度" },
    光标动画时间: { en: "Cursor animation time", "zh-HANT": "光標動畫時間" },
    更多: { en: "More", "zh-HANT": "更多" },
    行号: { en: "line number", "zh-HANT": "行號" },
    自动: { en: "auto", "zh-HANT": "自動" },
    "（识屏或直接打开主窗口，若文字为一行，则自动搜索）": {
        en: "(Sense screen or open main window directly, if text is one line, then search automatically)",
        "zh-HANT": "（識屏或直接打開主窗口，若文字為一行，則自動搜索）",
    },
    自动打开链接: { en: "auto open link", "zh-HANT": "自動打開鏈接" },
    自动搜索中文占比: { en: "Automatically search for Chinese percentage", "zh-HANT": "自動搜索中文佔比" },
    "（在中英混合中，数值越小，则整段文字越容易被程序认为是中文主要）": {
        en: "(In mixed Chinese and English, the smaller the value, the more likely the whole paragraph will be considered by the program to be rimarily in Chinese)",
        "zh-HANT": "（在中英混合中，數值越小，則整段文字越容易被程序認為是中文主要）",
    },
    文字搜索引擎: { en: "text search engine", "zh-HANT": "文字搜索引擎" },
    搜索引擎: { en: "Search engines", "zh-HANT": "搜索引擎" },
    百度: { en: "baidu", "zh-HANT": "百度" },
    翻译引擎: { en: "translation engines", "zh-HANT": "翻譯引擎" },
    默认引擎: { en: "default engine", "zh-HANT": "默認引擎" },
    记住引擎选择: { en: "Remember engine selection", "zh-HANT": "記住引擎選擇" },
    图像搜索引擎: { en: "image search engine", "zh-HANT": "圖像搜索引擎" },
    浏览器中打开: { en: "open in browser", "zh-HANT": "瀏覽器中打開" },
    "（点击搜索或翻译按钮后，将在系统默认浏览器打开搜索结果，否则在一个新的软件窗口打开）": {
        en: "(When you click the search or translate button, the search results will open in the system default browser, otherwise they will open in a new software window)",
        "zh-HANT": "（點擊搜索或翻譯按鈕後，將在系統默認瀏覽器打開搜索結果，否則在一個新的軟件窗口打開）",
    },
    打开后自动关闭软件浏览器: {
        en: "Automatically close the software browser after opening",
        "zh-HANT": "打開後自動關閉軟件瀏覽器",
    },
    "文字识别（OCR）": { en: "Text recognition (OCR)", "zh-HANT": "文字識別（OCR）" },
    离线OCR: { en: "offline OCR", "zh-HANT": "離線OCR" },
    有道: { en: "Youdao", "zh-HANT": "有道" },
    离线时切换离线OCR: { en: "Switch offline OCR when offline", "zh-HANT": "離線時切換離線OCR" },
    OCR检测: { en: "OCR detection", "zh-HANT": "OCR檢測" },
    "（每次启动时都提示OCR服务是否安装或开启）": {
        en: "(prompt for OCR service to be installed or turned on at each startup)",
        "zh-HANT": "（每次啟動時都提示OCR服務是否安裝或開啟）",
    },
    det模型: { en: "det model", "zh-HANT": "det模型" },
    rec模型: { en: "rec model", "zh-HANT": "rec模型" },
    字典: { en: "dictionary", "zh-HANT": "字典" },
    位置: { en: "location", "zh-HANT": "位置" },
    下载离线OCR: { en: "download offline OCR", "zh-HANT": "下載離線OCR" },
    删除离线OCR: { en: "delete offline OCR", "zh-HANT": "刪除離線OCR" },
    在线OCR: { en: "online OCR", "zh-HANT": "在線OCR" },
    "类型：": { en: "Type:", "zh-HANT": "類型：" },
    "位置版不起实质效果，但可以扩充免费使用次数:)": {
        en: "Location version does not have a substantial effect, but can be expanded for free usage :)",
        "zh-HANT": "位置版不起實質效果，但可以擴充免費使用次數:)",
    },
    高精度版: { en: "high-precision version", "zh-HANT": "高精度版" },
    高精度含位置版: { en: "High-precision version with location", "zh-HANT": "高精度含位置版" },
    标准版: { en: "Standard", "zh-HANT": "標準版" },
    标准含位置版: { en: "Standard with location", "zh-HANT": "標準含位置版" },
    手写文字: { en: "Handwritten text", "zh-HANT": "手寫文字" },
    公式: { en: "Formula", "zh-HANT": "公式" },
    "API Key：": { en: "API Key:", "zh-HANT": "API Key：" },
    "Secret Key：": { en: "Secret Key:", "zh-HANT": "Secret Key：" },
    "应用ID：": { en: "App ID:", "zh-HANT": "應用ID：" },
    "应用秘钥：": { en: "App Secret Key:", "zh-HANT": "應用秘鑰：" },
    保留截屏记录: { en: "Keep screenshots", "zh-HANT": "保留截屏記錄" },
    不勾选将不限次数保留: { en: "Uncheck to keep unlimited times", "zh-HANT": "不勾選將不限次數保留" },
    只保留: { en: "Keep only", "zh-HANT": "只保留" },
    次记录: { en: "record", "zh-HANT": "次記錄" },
    清空所有截屏记录: { en: "Clear all screenshots", "zh-HANT": "清空所有截屏記錄" },
    保留历史记录: { en: "Keep history", "zh-HANT": "保留歷史記錄" },
    自动清除历史记录: { en: "Automatically clear history", "zh-HANT": "自動清除歷史記錄" },
    天: { en: "days", "zh-HANT": "天" },
    小时: { en: "hours", "zh-HANT": "小時" },
    清空所有文字记录: { en: "Clear all text records", "zh-HANT": "清空所有文字記錄" },
    日期格式: { en: "date format", "zh-HANT": "日期格式" },
    代理: { en: "Proxy", "zh-HANT": "代理" },
    开启代理: { en: "proxy on", "zh-HANT": "開啟代理" },
    "pac文件：": { en: "pac file:", "zh-HANT": "pac文件：" },
    "代理规则：": { en: "proxy rules:", "zh-HANT": "代理規則：" },
    "排除规则：": { en: "Exclusion rules:", "zh-HANT": "排除規則：" },
    自动关闭窗口: { en: "autoclose window", "zh-HANT": "自動關閉窗口" },
    失去焦点后自动关闭: { en: "autoclose when focus is lost", "zh-HANT": "失去焦點後自動關閉" },
    "（不会触发跟随关闭）": { en: "(does not trigger follow close)", "zh-HANT": "（不會觸發跟隨關閉）" },
    主窗口: { en: "Main window", "zh-HANT": "主窗口" },
    搜索窗口: { en: "Search window", "zh-HANT": "搜索窗口" },
    "主窗口关闭后，所有搜索窗口跟随关闭": {
        en: "All search windows close after main window closes",
        "zh-HANT": "主窗口關閉後，所有搜索窗口跟隨關閉",
    },
    "所有搜索窗口关闭后，主窗口跟随关闭": {
        en: "Main window closes after all search windows close",
        "zh-HANT": "所有搜索窗口關閉後，主窗口跟隨關閉",
    },
    高级设置: { en: "Advanced settings", "zh-HANT": "高級設置" },
    "直接编辑设置源文件，更多自定义设置": {
        en: "Edit settings source file directly, more custom settings",
        "zh-HANT": "直接編輯設置源文件，更多自定義設置",
    },
    "（需要JSON知识）": { en: "(JSON knowledge required)", "zh-HANT": "（需要JSON知識）" },
    打开设置源文件: { en: "open settings source file", "zh-HANT": "打開設置源文件" },
    恢复默认设置: { en: "Restore default settings", "zh-HANT": "恢復默認設置" },
    不保存本次设置值: { en: "Do not save this setting", "zh-HANT": "不保存本次設置值" },
    "（若不清楚刚才更改了什么设置，请选中）": {
        en: "(Check if you're not sure what settings you just changed)",
        "zh-HANT": "（若不清楚剛才更改了什麼設置，請選中）",
    },
    硬件加速: { en: "Hardware acceleration", "zh-HANT": "硬件加速" },
    启用硬件加速: { en: "Enable hardware acceleration", "zh-HANT": "啟用硬件加速" },
    "（如果可用，且更改需要重启软件生效）": {
        en: "(if available and changes require a software restart to take effect)",
        "zh-HANT": "（如果可用，且更改需要重啟軟件生效）",
    },
    检查更新: { en: "Check for updates", "zh-HANT": "檢查更新" },
    启用检查更新: { en: "Enable check for updates", "zh-HANT": "啟用檢查更新" },
    "（仅在周末检查，且只在设置打开时检查）": {
        en: "(only check on weekends and only when settings are turned on)",
        "zh-HANT": "（僅在周末檢查，且只在設置打開時檢查）",
    },
    位置信息: { en: "Location information", "zh-HANT": "位置信息" },
    版本信息: { en: "version information", "zh-HANT": "版本信息" },
    "运行目录：": { en: "Operational directory:", "zh-HANT": "運行目錄：" },
    "配置目录：": { en: "Configuration Directory:", "zh-HANT": "配置目錄：" },
    "OCR 目录：": { en: "OCR Directory:", "zh-HANT": "OCR 目錄：" },
    "临时目录：": { en: "Temporary directory:", "zh-HANT": "臨時目錄：" },
    "文字记录：": { en: "Text records:", "zh-HANT": "文字記錄：" },
    "截屏记录：": { en: "Screenshot records:", "zh-HANT": "截屏記錄：" },
    "本机系统内核:": { en: "Local system kernel:", "zh-HANT": "本機系統內核:" },
    "识屏 · 搜索": { en: "Screen recognition · Search", "zh-HANT": "識屏 · 搜索" },
    "有新版本:": { en: "New version available:", "zh-HANT": "有新版本:" },
    暂无更新: { en: "No updates available at this time", "zh-HANT": "暫無更新" },
    "项目主页:": { en: "Project home page:", "zh-HANT": "項目主頁:" },
    更新日志: { en: "Update Log", "zh-HANT": "更新日誌" },
    错误报告与建议: { en: "Bug reports and suggestions", "zh-HANT": "錯誤報告與建議" },
    本软件遵循: { en: "This software follows", "zh-HANT": "本軟件遵循" },
    本软件基于: { en: "This software is based on", "zh-HANT": "本軟件基於" },
    这些软件: { en: "these software", "zh-HANT": "這些軟件" },
};


// var a = Object.keys(obj).join("\n");
// 复制到翻译器翻译
// var b = "".split("\n");
// var n = 0;
// for (let i in obj) {
//     obj[i]["zh-S"] = b[n];
//     n++;
// }
// JSON.stringify(obj);
