module.exports = {
    t,
    lan,
};

var language = "";
var l2l = {
    "en-GB": "en",
    "en-UK": "en",
};

/**
 * 切换语言
 * @param {string} lan 语言
 */
function lan(lan) {
    language = lan;
}

/**
 * 翻译
 * @param {string} text 原文字
 * @returns 翻译后的文字
 */
function t(text) {
    return obj?.[text]?.[language] || obj?.[text]?.[l2l[language]] || text;
}

var obj = {
    // main
    "服务正在下载中……": { en: "Service download is in progress ......" },
    服务下载已取消: { en: "Service download has been cancelled" },
    服务已下载: { en: "Service has been downloaded" },
    "，正准备安装相关的依赖，请允许安装": {
        en: ", is preparing to install the relevant dependencies, please allow installation",
    },
    自动搜索: { en: "Automatic search" },
    截屏搜索: { en: "Screenshot search" },
    选中搜索: { en: "Selected search" },
    剪贴板搜索: { en: "Clipboard search" },
    失焦关闭: { en: "Out of focus off" },
    主界面: { en: "Main screen" },
    搜索界面: { en: "Search screen" },
    浏览器打开: { en: "Browser open" },
    主页面: { en: "Main Page" },
    设置: { en: "Settings" },
    教程帮助: { en: "Tutorial Help" },
    重启: { en: "Restart" },
    退出: { en: "Exit" },
    已经在后台启动: { en: "Already started in background" },
    服务未下载: { en: "Service not downloaded" },
    "离线OCR 服务未安装": { en: "Offline OCR service is not installed" },
    需要下载才能使用: { en: "Need to download to use" },
    不再提示: { en: "No more prompts" },
    "下载(约": { en: "Download (approx." },
    "前往 设置": { en: "Go to Settings" },
    取消: { en: "Cancel" },
    服务需要升级: { en: "Service needs to be upgraded" },
    "离线OCR 服务版本较旧": { en: "Older version of offline OCR service" },
    服务下载失败: { en: "Service download failed" },
    "离线OCR 服务版本下载失败": { en: "Offline OCR service version download failed" },
    请前往网站手动下载: { en: "Please go to the website to download manually" },
    警告: { en: "Warning" },
    无法识别二维码: { en: "QR code not recognised" },
    请尝试重新识别: { en: "Please try to re-identify" },
    选择要打开应用的位置: { en: "Select where you want to open the app" },
    选择要保存的位置: { en: "Select a location to save" },
    图像: { en: "Image" },
    保存图像失败: { en: "Failed to save image" },
    用户已取消保存: { en: "User has cancelled the save" },
    视频: { en: "Video" },
    保存视频失败: { en: "Failed to save video" },
    错误: { en: "Error" },
    重启: { en: "Reboot" },
    "已恢复默认设置，部分设置需要重启": {
        en: "Default settings have been restored, some settings need to be rebooted",
    },
    生效: { en: "Effective" },
    稍后: { en: "Later" },
    关于: { en: "About" },
    设置: { en: "Settings" },
    服务: { en: "Services" },
    隐藏: { en: "Hide" },
    隐藏其他: { en: "Hide other" },
    全部显示: { en: "Show all" },
    文件: { en: "File" },
    保存到历史记录: { en: "Save to history" },
    其他编辑器打开: { en: "Open with other editor" },
    "打开方式...": { en: "Open as..." },
    关闭: { en: "Close" },
    编辑: { en: "Edit" },
    打开链接: { en: "Open link" },
    搜索: { en: "Search" },
    翻译: { en: "Translate" },
    撤销: { en: "Undo" },
    重做: { en: "Redo" },
    剪切: { en: "Cut" },
    复制: { en: "Copy" },
    粘贴: { en: "Paste" },
    删除: { en: "Delete" },
    全选: { en: "Select All" },
    自动删除换行: { en: "Auto Delete Line Feed" },
    查找: { en: "Find" },
    替换: { en: "Replace" },
    自动换行: { en: "Auto Line Feed" },
    拼写检查: { en: "Spell check" },
    朗读: { en: "Read aloud" },
    开始朗读: { en: "Start reading aloud" },
    停止朗读: { en: "Stop reading aloud" },
    浏览器: { en: "Browser" },
    后退: { en: "Back" },
    前进: { en: "Forward" },
    刷新: { en: "Refresh" },
    停止加载: { en: "Stop loading" },
    浏览器打开: { en: "Browser open" },
    保存到历史记录: { en: "Save to history" },
    视图: { en: "View" },
    重新加载: { en: "Reload" },
    强制重载: { en: "Force Reload" },
    开发者工具: { en: "Developer Tools" },
    历史记录: { en: "History" },
    实际大小: { en: "Actual size" },
    放大: { en: "Zoom In" },
    缩小: { en: "Zoom out" },
    全屏: { en: "Full screen" },
    窗口: { en: "Window" },
    最小化: { en: "Minimise" },
    关闭: { en: "Close" },
    置于最前面: { en: "Place at top" },
    帮助: { en: "Help" },
    教程帮助: { en: "Tutorial help" },
    保存图像成功: { en: "Saved image successfully" },
    已保存图像到: { en: "Saved image to" },
    选择要保存的位置: { en: "Select a location to save to" },
    "eSearch - 设置": { en: "eSearch - Setting" },
    查找: { en: "find" },
    上一个匹配: { en: "previous match" },
    下一个匹配: { en: "next match" },
    启动: { en: "boot" },
    开机自启动: { en: "boot-up" },
    启动提示: { en: "boot prompt" },
    启动时系统通知提示启动: { en: "System notification to start at boot" },
    语言: { en: "Language" },
    使用系统语言: { en: "use system language" },
    快捷键: { en: "shortcuts" },
    全局: { en: "global" },
    截屏: { en: "Screenshot" },
    主搜索功能: { en: "Main search function" },
    自动搜索排除: { en: "Automatic search exclusion" },
    "若选中的文字符合文本框的规则，将使用截屏搜索而不是选择搜索": {
        en: "if the selected text matches the rules of the text box, a screenshot search will be used instead of a select search",
    },
    "换行新建项目，支持正则表达式": { en: "New item with line feed, regular expression support" },
    剪贴板搜索: { en: "clipboard search" },
    使用选区内容: { en: "Using the contents of a selection" },
    全局样式: { en: "global styles" },
    毛玻璃效果: { en: "Glass effect" },
    模糊: { en: "blur" },
    不透明度: { en: "Opacity" },
    深色模式: { en: "dark mode" },
    跟随系统: { en: "following system" },
    浅色: { en: "light" },
    深色: { en: "dark" },
    全局缩放: { en: "global zoom" },
    字体: { en: "Font" },
    主要字体: { en: "main fonts" },
    "（适用于主界面等文字字体）": { en: "(for text fonts such as main interface)" },
    等宽字体: { en: "Equal width fonts" },
    "（适用于截屏时数字、颜色代码等字体）": {
        en: "(for fonts such as numbers, colour codes, etc. when taking screenshots)",
    },
    工具栏: { en: "Toolbar" },
    工具栏跟随: { en: "toolbar follow" },
    展示内容优先: { en: "priority for displaying content" },
    效率优先: { en: "efficiency first" },
    按钮大小: { en: "Button size" },
    按钮: { en: "Button" },
    图标比例: { en: "icon scale" },
    取色器: { en: "colour picker" },
    大小: { en: "size" },
    取色器大小: { en: "color picker size" },
    像素大小: { en: "pixel size" },
    默认格式: { en: "default format" },
    框选: { en: "Boxed" },
    框选颜色: { en: "box color" },
    遮罩颜色: { en: "mask color" },
    选区颜色: { en: "selection color" },
    光标: { en: "cursor" },
    "以(0,0)为起点": { en: "starting at (0,0)" },
    "以(1,1)为起点": { en: "starting at (1,1)" },
    大小坐标: { en: "size coordinates" },
    显示四角坐标: { en: "display quadrangular coordinates" },
    "（截屏框选附近除了框选大小，还会加上左上角和右下角坐标）": {
        en: "(screenshot boxed near will add top-left and bottom-right coordinates in addition to the boxed size)",
    },
    框选后默认操作: { en: "default action after frame" },
    "框选完鼠标松开一瞬间，执行操作": { en: "action to be performed the moment the mouse is released after framing" },
    无: { en: "none" },
    "OCR(文字识别)": { en: "OCR (text recognition)" },
    以图搜图: { en: "Search by image" },
    QR码: { en: "QR code" },
    标记: { en: "Marker" },
    其他应用打开: { en: "open in other apps" },
    放在屏幕上: { en: "Place on screen" },
    复制: { en: "Copy" },
    保存: { en: "Save" },
    自动框选: { en: "Automatically frame" },
    "使用OpenCV自动识别边缘轮廓（测试版）": { en: "Automatic edge contour recognition using OpenCV (beta)" },
    启用自动框选: { en: "Enable auto-framing" },
    边缘识别高级设置: { en: "Advanced settings for edge recognition" },
    最小阈值: { en: "minimum threshold" },
    最大阈值: { en: "maximum threshold" },
    图像编辑: { en: "Image editing" },
    默认属性: { en: "default properties" },
    填充颜色: { en: "Fill color" },
    边框颜色: { en: "border color" },
    边框宽度: { en: "border width" },
    画笔颜色: { en: "brush color" },
    画笔粗细: { en: "brush thickness" },
    复制偏移: { en: "copy offset" },
    "复制完一个元素后，为了分辨，可以让其偏移": { en: "after copying an element, you can offset it to distinguish" },
    x轴: { en: "x-axis" },
    y轴: { en: "y-axis" },
    快速截屏: { en: "quick screenshot" },
    保存到: { en: "save to" },
    剪贴板: { en: "clipboard" },
    目录: { en: "directory" },
    获取保存路径: { en: "get save path" },
    录屏: { en: "record screen" },
    自动录制: { en: "auto record" },
    开启自动录制: { en: "Enable auto-recording" },
    录制: { en: "record" },
    视频比特率: { en: "video bitrate" },
    屏幕: { en: "screen" },
    帧率: { en: "frame rate" },
    高级: { en: "Advanced" },
    "换行新建项目，%s代替关键字": { en: "line feed new item, %s instead of keyword" },
    摄像头: { en: "camera" },
    默认开启: { en: "default on" },
    记录开启状态: { en: "record on status" },
    "换行新建项目，%s代替关键字": { en: "New item in new line, %s instead of keyword" },
    音频: { en: "Audio" },
    "换行新建项目，%s代替关键字": { en: "New item in new line, %s instead of keyword" },
    保存: { en: "Save" },
    文件名称: { en: "file name" },
    时间: { en: "time" },
    "预览:": { en: "Preview:" },
    时间代码: { en: "timecode" },
    四位数年: { en: "four-digit year" },
    末两位年: { en: "Last two digit year" },
    月: { en: "month" },
    日: { en: "day" },
    星期: { en: "Week" },
    "24小时制小时": { en: "24-hour hour" },
    "12小时制小时": { en: "12-hour hour" },
    分: { en: "minutes" },
    秒: { en: "seconds" },
    毫秒: { en: "milliseconds" },
    默认格式: { en: "default format" },
    jpg质量: { en: "jpg quality" },
    编辑器: { en: "editor" },
    字体: { en: "Font" },
    字体大小: { en: "font size" },
    记住主界面字体大小: { en: "remember main interface font size" },
    样式: { en: "style" },
    Tab制表符宽度: { en: "Tab tab width" },
    光标动画时间: { en: "Cursor animation time" },
    更多: { en: "More" },
    自动换行: { en: "Auto Line Feed" },
    拼写检查: { en: "spell check" },
    行号: { en: "line number" },
    搜索: { en: "Search" },
    自动: { en: "auto" },
    自动搜索: { en: "auto search" },
    "（识屏或直接打开主窗口，若文字为一行，则自动搜索）": {
        en: "(Sense screen or open main window directly, if text is one line, then search automatically)",
    },
    自动打开链接: { en: "auto open link" },
    自动搜索中文占比: { en: "Automatically search for Chinese percentage" },
    "（在中英混合中，数值越小，则整段文字越容易被程序认为是中文主要）": {
        en: "(In mixed Chinese and English, the smaller the value, the more likely the whole paragraph will be considered by the program to be rimarily in Chinese)",
    },
    文字搜索引擎: { en: "text search engine" },
    搜索引擎: { en: "Search engines" },
    百度: { en: "Baidu" },
    "换行新建项目，%s代替关键字": { en: "line break new item, %s instead of keyword" },
    翻译引擎: { en: "translation engines" },
    "换行新建项目，%s代替关键字": { en: "new item in new line, %s instead of keyword" },
    默认引擎: { en: "default engine" },
    记住引擎选择: { en: "remember engine selection" },
    图像搜索引擎: { en: "image search engine" },
    记住引擎选择: { en: "remember engine selection" },
    浏览器中打开: { en: "open in browser" },
    浏览器中打开: { en: "open in browser" },
    "（点击搜索或翻译按钮后，将在系统默认浏览器打开搜索结果，否则在一个新的软件窗口打开）": {
        en: "(When you click the search or translate button, the search results will open in the system default browser, otherwise they will open in a new software window)",
    },
    打开后自动关闭软件浏览器: { en: "Automatically close the software browser after opening" },
    "文字识别（OCR）": { en: "Text recognition (OCR)" },
    离线OCR: { en: "Offline OCR" },
    有道: { en: "Youdao" },
    记住引擎选择: { en: "Remember engine selection" },
    离线时切换离线OCR: { en: "Switch offline OCR when offline" },
    离线OCR: { en: "offline OCR" },
    OCR检测: { en: "OCR detection" },
    "（每次启动时都提示OCR服务是否安装或开启）": {
        en: "(prompt for OCR service to be installed or turned on at each startup)",
    },
    det模型: { en: "det model" },
    rec模型: { en: "rec model" },
    字典: { en: "dictionary" },
    目录: { en: "directory" },
    位置: { en: "location" },
    下载离线OCR: { en: "download offline OCR" },
    删除离线OCR: { en: "delete offline OCR" },
    在线OCR: { en: "online OCR" },
    百度: { en: "baidu" },
    "类型：": { en: "Type:" },
    "位置版不起实质效果，但可以扩充免费使用次数:)": {
        en: "Location version does not have a substantial effect, but can be expanded for free usage :)",
    },
    高精度版: { en: "high-precision version" },
    高精度含位置版: { en: "High-precision version with location" },
    标准版: { en: "Standard" },
    标准含位置版: { en: "Standard with location" },
    手写文字: { en: "Handwritten text" },
    公式: { en: "Formula" },
    "API Key：": { en: "API Key:" },
    "Secret Key：": { en: "Secret Key:" },
    "应用ID：": { en: "App ID:" },
    "应用秘钥：": { en: "App Secret Key:" },
    历史记录: { en: "History" },
    截屏: { en: "Screenshot" },
    保留截屏记录: { en: "Keep screenshots" },
    不勾选将不限次数保留: { en: "Uncheck to keep unlimited times" },
    只保留: { en: "Keep only" },
    次记录: { en: "record" },
    清空所有截屏记录: { en: "Clear all screenshots" },
    搜索: { en: "Search" },
    保留历史记录: { en: "Keep history" },
    自动清除历史记录: { en: "Automatically clear history" },
    天: { en: "days" },
    小时: { en: "hours" },
    清空所有文字记录: { en: "Clear all text records" },
    日期格式: { en: "date format" },
    代理: { en: "Proxy" },
    开启代理: { en: "proxy on" },
    "pac文件：": { en: "pac file:" },
    "代理规则：": { en: "proxy rules:" },
    "排除规则：": { en: "Exclusion rules:" },
    自动关闭窗口: { en: "autoclose window" },
    失去焦点后自动关闭: { en: "autoclose when focus is lost" },
    "（不会触发跟随关闭）": { en: "(does not trigger follow close)" },
    主窗口: { en: "Main window" },
    搜索窗口: { en: "Search window" },
    "主窗口关闭后，所有搜索窗口跟随关闭": { en: "All search windows close after main window closes" },
    "所有搜索窗口关闭后，主窗口跟随关闭": { en: "Main window closes after all search windows close" },
    高级: { en: "Advanced" },
    高级设置: { en: "Advanced settings" },
    "直接编辑设置源文件，更多自定义设置": { en: "Edit settings source file directly, more custom settings" },
    "（需要JSON知识）": { en: "(JSON knowledge required)" },
    打开设置源文件: { en: "open settings source file" },
    恢复默认设置: { en: "Restore default settings" },
    不保存本次设置值: { en: "Do not save this setting" },
    "（若不清楚刚才更改了什么设置，请选中）": { en: "(Check if you're not sure what settings you just changed)" },
    硬件加速: { en: "Hardware acceleration" },
    启用硬件加速: { en: "Enable hardware acceleration" },
    "（如果可用，且更改需要重启软件生效）": {
        en: "(if available and changes require a software restart to take effect)",
    },
    检查更新: { en: "Check for updates" },
    启用检查更新: { en: "Enable check for updates" },
    "（仅在周末检查，且只在设置打开时检查）": { en: "(only check on weekends and only when settings are turned on)" },
    位置信息: { en: "Location information" },
    版本信息: { en: "version information" },
    "运行目录：": { en: "Operational directory:" },
    "配置目录：": { en: "Configuration Directory:" },
    "OCR 目录：": { en: "OCR Directory:" },
    "临时目录：": { en: "Temporary directory:" },
    "文字记录：": { en: "Text records:" },
    "截屏记录：": { en: "Screenshot records:" },
    "本机系统内核:": { en: "Local system kernel:" },
    "识屏 · 搜索": { en: "Screen recognition · Search" },
    "有新版本:": { en: "New version available:" },
    暂无更新: { en: "No updates available at this time" },
    "项目主页:": { en: "Project home page:" },
    更新日志: { en: "Update Log" },
    错误报告与建议: { en: "Bug reports and suggestions" },
    本软件遵循: { en: "This software follows" },
    本软件基于: { en: "This software is based on" },
    这些软件: { en: "these software" },
    关于: { en: "About" },
    检查更新: { en: "Check for updates" },
};
